version: '3.3'
services:
  chrome_provider:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
    - "5900:5900"
    volumes:
    - /dev/shm:/dev/shm
  firefox_provider:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
    - "5901:5900"
    volumes:
    - /dev/shm:/dev/shm
  test_runner:
    image: python:3.8
    environment:
    - BROWSER=chrome
    tty: true
    volumes:
    - ./tests:/test_source/tests
    working_dir: /test_source

