#!/bin/bash

# Install test requirements
pip3 install -r tests/system/requirements.txt

# Run system tests
find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
[ -e tests/system/output/results.json ] && rm tests/system/output/results.json

behave -s tests/system/features --no-logcapture -f json -o tests/system/output/results.json "$@"

if [[ $? = 0 ]]; then
    echo ""
    echo "#################################"
    echo "###### SYSTEM TESTS PASSED ######"
    echo "#################################"
    echo ""
    TEST_PASSED=1
else
    echo ""
    echo "#################################"
    echo "###### SYSTEM TESTS FAILED ######"
    echo "#################################"
    echo ""
fi

if [[ -z $TEST_PASSED ]]
then
    exit 1
fi
